### ISSUE TITLE
Cant create new examination slot in edge browser

### ISSUE THREAD

**Issue by rishimadan14** [aniruddh622003/UPES-ParikshaMitr-Controller-Frontend#11]
Url/page where bug occurred: http://localhost:3000/main/slots
Steps to Reproduce: open http://localhost:3000/main/slots in Edge Browser, Add slot, set date to 31st March 2024
Expected result: It should create slot
Actual result: gives 500 error
Severity - minor/major/critical: critical
Additional notes: fix please
![WhatsApp Image 2024-03-07 at 20 39 58_5c462ffe](https://github.com/aniruddh622003/UPES-ParikshaMitr-Controller-Frontend/assets/76414582/1e21e1bf-a713-430e-a0bf-b020fc4eb20a)

**Comment by aniruddh622003** [comment]
Can not reproduce the same.
Working fine on my side
@rishimadan14

**Comment by aniruddh622003** [comment]
Found the bug. Solved it in fdc53ed

**Comment by rishimadan14** [comment]
issue resolved
