### ISSUE TITLE
[FEATURE] Create single room to slot and all single student to room

### ISSUE THREAD

**Issue by aniruddh622003** [aniruddh622003/UPES-ParikshaMitr-Controller-Frontend#16]
Controller should be able to add single room to slot manually and also add single children to rooms manually.

**Comment by aniruddh622003** [comment]
Student will only be allowed to be added if SAP ID is not present in the entire slot.

**Comment by khushigupta2512** [comment]
completed in 569f1ed

**Comment by khushigupta2512** [comment]
made minor changes in 6ef57c2
