### ISSUE TITLE
enhancement on student list

### ISSUE THREAD

**Issue by rishimadan14** [aniruddh622003/UPES-ParikshaMitr-Controller-Frontend#17]
URL/page where enhancement needed: http://localhost:3000/main/studentList/65eb9f452ed38a06e328cea2
Steps to Reproduce: open http://localhost:3000/main/slots, open actions for particular slot then click on actions to open student details
Expected result: should show a refresh icon on the top right side of student list to update the latest attendance data
Actual result: now we have to go back to the previous slot details page and refresh there, then come back to see latest attendance data
Severity - minor/major/critical: major
Additional notes: add please
![image](https://github.com/aniruddh622003/UPES-ParikshaMitr-Controller-Frontend/assets/76414582/fd8c7f53-e41d-41f3-a4e6-49ee3e18ed23)

**Comment by aniruddh622003** [comment]
The attendance data is live, refreshes in around 2-5 mins. But need for realtime attendance refresh is practically useless as a controller will not need to view realtime attendance of data
