### ISSUE TITLE
[BUG] while filtering fields they start moving

### ISSUE THREAD

**Issue by rishimadan14** [aniruddh622003/UPES-ParikshaMitr-Controller-Frontend#22]
**Describe the bug**
In the ufm list section of the controller frontend when we select actions of a particular slot and go to that page and try filtering by clicking on the menu icon infront of column names, the fields automatically starts moving to right

**To Reproduce**
1. Go to 'http://localhost:3000/main/ufm/65ede88c4921b0d65816ac5e'
2. Click on 'menu icon on any column name'
3. Scroll down to 'filter' and search on basis

**Expected behavior**
still behaviour and desired  output based on parameter

**Actual behaviour**
after starting to input the filter field the fields start to move rightwards.

**Screenshots**
![image](https://github.com/aniruddh622003/UPES-ParikshaMitr-Controller-Frontend/assets/76414582/2c3eae86-2f76-4f3b-9fa2-35f1d3c56f4d)

**Additional context**
none

**Comment by aniruddh622003** [comment]
No title
