### ISSUE TITLE
[BUG] different number of invigilator shows than assigned

### ISSUE THREAD

**Issue by rishimadan14** [aniruddh622003/UPES-ParikshaMitr-Controller-Frontend#24]
**Describe the bug**
In slot details when we open the actions of a particular slot and in that slot there we have 2 invigilators assigned but above it is showing only one invigilator in total though 2 are assigned.

**To Reproduce**
1. Go to 'http://localhost:3000/main/slotDetail/65ede88c4921b0d65816ac5e'
2. view the 'slot details'
3. See under invigilators only 1 no. is showing though two are assigned

**Expected behavior**
should show two invigilators assigned

**Actual behaviour**
shows only 1 invigilator assigned

**Screenshots**
![image](https://github.com/aniruddh622003/UPES-ParikshaMitr-Controller-Frontend/assets/76414582/5fba460f-6973-4593-80e0-614028e1c5ee)

**Additional context**
none

**Comment by aniruddh622003** [comment]
Hi Rishi,
Please take pull for recent changes before creating any bug report

**Comment by rishimadan14** [comment]
bog fixed
